---
abstract: 'Non-blocking Redis client with auto reconnect feature'
author:
  - 'Eugene Ponizovsky <ponizovsky@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Redis-RipeRedis
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 0
  Carp: 0
  Encode: 0
  Scalar::Util: 0
  Test::MockObject: 0
  Test::More: 0
version: 0.807100
