---
abstract: 'Flexible non-blocking Redis client with reconnect'
author:
  - 'Eugene Ponizovsky <ponizovsky@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Redis-RipeRedis
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 6.01
  Carp: 0
  Digest::SHA1: 0
  Encode: 0
  Scalar::Util: 0
  Test::MockObject: 0
  Test::More: 0
  perl: 5.006000
resources:
  bugtracker: https://github.com/iph0/AnyEvent-Redis-RipeRedis/issues
  homepage: https://github.com/iph0/AnyEvent-Redis-RipeRedis
  license: http://dev.perl.org/licenses/
  repository: https://github.com/iph0/AnyEvent-Redis-RipeRedis
version: 1.212
