---
abstract: 'Flexible non-blocking Redis client with reconnect'
author:
  - 'Eugene Ponizovsky <ponizovsky@gmail.com>'
build_requires:
  Test::Fatal: 0.013
  Test::More: 0.98
  Test::RedisServer: 0.14
  Test::TCP: 2.02
configure_requires:
  ExtUtils::MakeMaker: 6.64
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Redis-RipeRedis
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 6.01
  Carp: 0
  Digest::SHA: 0
  Encode: 0
  Scalar::Util: 0
  perl: 5.008000
resources:
  bugtracker: https://github.com/iph0/AnyEvent-Redis-RipeRedis/issues
  homepage: https://github.com/iph0/AnyEvent-Redis-RipeRedis
  license: http://dev.perl.org/licenses/
  repository: https://github.com/iph0/AnyEvent-Redis-RipeRedis
version: 1.41_04
